#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

runcmd:
  - iptables -P INPUT ACCEPT && iptables -P FORWARD ACCEPT && iptables -P OUTPUT ACCEPT
  - iptables -F
  - iptables -X
  - iptables -Z
  - iptables -t nat -F && iptables -t nat -X && iptables -t mangle -F && iptables -t mangle -X && iptables -t raw -F && iptables -t raw -X
  - apt-get install -y apt-transport-https ca-certificates curl
  - curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
  - echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /"| tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
  - echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/xUbuntu_22.04/ /"| tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:1.25.list
  - curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.25/xUbuntu_22.04/Release.key | apt-key add -
  - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key | apt-key add -
  - apt-get update && apt-get install -y kubelet kubeadm kubectl cri-o cri-o-runc
  - sysctl -w net.ipv4.ip_forward=1
  - echo "br_netfilter" > /etc/modules && modprobe br_netfilter
  - systemctl enable --now crio
  - kubeadm init --pod-network-cidr=10.123.0.0/16 --certificate-renewal=true
  - mkdir -p /root/.kube
  - cp -i /etc/kubernetes/admin.conf /root/.kube/config
  - kubectl --kubeconfig /root/.kube/config taint nodes --all node-role.kubernetes.io/control-plane-
  - kubectl --kubeconfig /root/.kube/config apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  - sleep 10 && KUBE_EDITOR="sed -i 's/metric-resolution=15s/metric-resolution=15s\n        - --kubelet-insecure-tls=true/g'" kubectl --kubeconfig /root/.kube/config edit deployments.apps -n kube-system metrics-server
  - sleep 10 && kubectl --kubeconfig /root/.kube/config create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/tigera-operator.yaml
  - sleep 10 && curl https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/custom-resources.yaml | sed "s/192.168.0.0/10.123.0.0/g" | kubectl --kubeconfig /root/.kube/config create -f -
