#cloud-config
package_upgrade: true
package_reboot_if_required: true

apt:
  preserve_sources_list: true
  sources:
    kubernetes.list:
      keyid: A362B822F6DEDC652817EA46B53DC80D13EDEF05
      source: "deb [signed-by=$KEY_FILE] https://packages.cloud.google.com/apt/ kubernetes-xenial main"

    libcontainers.list:
      keyid: 2472D6D0D2F66AF87ABA8DA34D64390375060AA4
      source: "deb [signed-by=$KEY_FILE] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /"

    cri-o_{{ crio_version }}.list:
      keyid: 2472D6D0D2F66AF87ABA8DA34D64390375060AA4
      source: "deb [signed-by=$KEY_FILE] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/xUbuntu_22.04/ /"

write_files:
  - path: /etc/hosts
    append: true
    content: |
      {%- for host in etc_hosts %}
      {{ host.private_ip }} {{ host.hostname }}
      {{ host.wg_ip }} {{ host.hostname }}
      {%- endfor %}
  - path: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
  - path: /etc/sysctl.d/k8s.conf
    content: |
      # Network Settings
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.conf.all.proxy_arp = 1
      net.ipv4.conf.all.forwarding = 1

      # Filesystem and Disk I/O
      vm.dirty_ratio = 10
      vm.swappiness = 10

      # Memory Management
      vm.overcommit_memory = 1
      vm.min_free_kbytes = 65536

      # Process Scheduling
      kernel.sched_min_granularity_ns = 10000000
      kernel.sched_wakeup_granularity_ns = 15000000

      # TCP/IP Settings
      net.ipv4.tcp_keepalive_time = 600
      net.ipv4.tcp_tw_reuse = 1

      # Security
      kernel.randomize_va_space = 2
      kernel.sysrq = 0
  - path: /etc/default/kubelet
    content: |
      KUBELET_EXTRA_ARGS="--node-ip={{ cluster_advertise_address }}"
  - path: /etc/wireguard/wg0.conf
    permissions: "0600"
    content: |
      {{ wireguard_config | indent(6) }}

packages:
  - cri-o
  - cri-o-runc
  - kubelet
  - kubeadm
  - kubectl
  - wireguard

runcmd:
  # Disable the following line to stop logging all dropped packets
  - iptables -I INPUT -m limit --limit 5/min -j LOG --log-prefix "packet-drop " --log-level 7
  - iptables-save | grep -v "DROP" | grep -v "REJECT" | iptables-restore
  - iptables -I INPUT -i wg0 -j ACCEPT
  - iptables -I INPUT -i lo -j ACCEPT
  - sysctl --system
  - modprobe -a overlay br_netfilter
  - netfilter-persistent save
  - systemctl restart iptables
  - systemctl enable --now wg-quick@wg0
  - systemctl enable --now crio
